import React from 'react';

export default function ThoughtsPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold mb-6 text-white">Earthie's Thoughts</h1>
      <p className="text-lg text-gray-300">
        Welcome to the thoughts page! Here you'll find articles and insights generated by Earthie, our AI companion.
      </p>
      {/* Placeholder for future article list */}
      <div className="mt-8 p-6 border border-earthie-dark-light rounded-xl bg-earthie-dark-light/50">
        <h2 className="text-2xl font-semibold mb-4 text-white">Coming Soon...</h2>
        <p className="text-gray-400">
          Earthie is busy writing! Check back soon for interesting articles about Earth2 and more.
        </p>
      </div>
    </div>
  );
} 